### PR TITLE
Added 'deletestart' and 'deletestop' events

### PR DESCRIPTION
**Pull request by octavm**

### CODE REVIEW

**Comment by mstahv** [comment]
Is this no more valid?

Sorry I haven't found time to handle this. I have been mostly working with the v-leaflet-editable version. If you use this add-on more actively, maybe we should make you the maintainer?

**Comment by mstahv** [comment]
I added you commit rights to this repository. If you want, I can also as to transfer the "ownership" in Directory to you (must be currently done with DB, but I know the administrator ;-) ).

**Comment by octavm** [comment]
Yes, that would be super great. It will allow me to add new v-leaflet-draw releases to Directory ?

**Comment by mstahv** [comment]
Yep, that would be the plan. In future version of the Directory there will hopefully be an option to let multiple people maintain one add-on. Can you share me the email you are using in you vaadin.com (my email: matti ät vaadin.com)?

**Comment by octavm** [comment]
My vaadin account is using email: octavm ät startmail.com

**Pull request closed without merging**
